# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebc_user',
                'managed': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebc_user_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(default=1, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_department',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_employee_status',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_employee_table',
            },
        ),
        migrations.CreateModel(
            name='InquiryActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_inquiry_activity',
            },
        ),
        migrations.CreateModel(
            name='InquirySources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_inquiry_services',
            },
        ),
        migrations.CreateModel(
            name='InquiryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_inquiry_status',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(default=1, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebc_location',
            },
        ),
        migrations.CreateModel(
            name='NotificationReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('user_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_notification_read_log',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('imagePath', models.URLField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_notifications',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('response_time', models.PositiveIntegerField()),
                ('threshold_time', models.PositiveIntegerField()),
                ('is_active', models.CharField(default=1, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Categories')),
            ],
            options={
                'db_table': 'ebc_services',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ebc_task_status',
            },
        ),
        migrations.AddField(
            model_name='notificationreadlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Notifications'),
        ),
    ]
