# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20170808_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
